# security:
#     providers:
#         in_memory:
#             memory: ~

#     firewalls:
#         dev:
#             pattern: ^/(_(profiler|wdt)|css|images|js)/
#             security: false

#         default:
#             anonymous: ~
# security:
#     encoders:
#         Glr\UserBundle\Entity\User:
#             algorithm: sha1
#             encode-as-base64: false
#             iterations: 1

#     role_hierarchy:
#         ROLE_ADMIN:       ROLE_USER
#         ROLE_SUPER_ADMIN: ROLE_ADMIN

#     providers:
#         user_db:
#             entity: { class: Glr\UserBundle\Entity\User, property: email }

#     firewalls:
#         main:
#             pattern: ^/
#             form_login:
#                 provider: user_db
#                 csrf_provider: form.csrf_provider
#             logout:       true
#             anonymous:    true

#     access_control:
#         - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#         - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
#         - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#         - { path: ^/admin/, role: ROLE_ADMIN }
#         - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }

security:
    encoders:
        Glr\UserBundle\Entity\User:
            algorithm: sha1
            encode-as-base64: false
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }